#ifndef STARLIGHT_KEYSHORTNAMES_H_
#define STARLIGHT_KEYSHORTNAMES_H_

#include <allegro5\keycodes.h>

namespace starlight
{
	enum KEYBOARD_KEYS
	{
		KEY_UP			= ALLEGRO_KEY_UP,
		KEY_DOWN		= ALLEGRO_KEY_DOWN,
		KEY_LEFT		= ALLEGRO_KEY_LEFT,
		KEY_RIGHT		= ALLEGRO_KEY_RIGHT,
		KEY_W			= ALLEGRO_KEY_W,
		KEY_S			= ALLEGRO_KEY_S,
		KEY_A			= ALLEGRO_KEY_A,
		KEY_D			= ALLEGRO_KEY_D,

		KEY_C			= ALLEGRO_KEY_C,
		KEY_I			= ALLEGRO_KEY_I,
		KEY_M			= ALLEGRO_KEY_M,
		KEY_P			= ALLEGRO_KEY_P,
		KEY_F1			= ALLEGRO_KEY_F1,
		KEY_F2			= ALLEGRO_KEY_F2,
		KEY_F3			= ALLEGRO_KEY_F3,
		KEY_SPACE		= ALLEGRO_KEY_SPACE,
		KEY_ESC			= ALLEGRO_KEY_ESCAPE
	};

	enum KEY_MODIFIER
	{
		KEYMOD_SHIFT	= ALLEGRO_KEYMOD_SHIFT,
		KEYMOD_CTRL		= ALLEGRO_KEYMOD_CTRL,
		KEYMOD_ALT		= ALLEGRO_KEYMOD_ALT
	};

	enum MOUSE_BUTTONS
	{
		MOUSE_BUTTON_LEFT = 1,
		MOUSE_BUTTON_RIGHT,
		MOUSE_BUTTON_MIDDLE
	};
}

#endif //STARLIGHT_KEYSHORTNAMES_H_